openapi: 3.0.3
info:
  title: ticket show app
  description:
    <h2> venue Table  </h2> 
      <table>
        <thead>
          <th>Column Name</th>
          <th>Column Type</th>
          <th>Constraints</th>
        </thead>
        <tbody>
          <tr>
            <td>vid</td>
            <td>Integer</td>
            <td>Primary Key, Auto Increment</td>
          </tr>
          <tr>
            <td>venue</td>
            <td>String</td>
            <td>-</td>
          </tr>
           <tr>
            <td>loc</td>
            <td>String</td>
            <td>-</td>
          </tr>
           <tr>
            <td>cap</td>
            <td>integer</td>
            <td>-</td>
          </tr>
          
          
        </tbody>
      </table>

    <h2> show table </h2> 
      <table>
        <thead>
          <th>Column Name</th>
          <th>Column Type</th>
          <th>Constraints</th>
        </thead>
        <tbody>
          <tr>
            <td>id</td>
            <td>Integer</td>
            <td>Primary Key, Auto Increment</td>
          </tr>
          <tr>
            <td>showname</td>
            <td>String</td>
            <td>-</td>
          </tr>
          <tr>
            <td>sid</td>
            <td>integer</td>
            <tdprimary key></td>
          </tr>      
          <tr>
            <td>rating</td>
            <td>integer</td>
            <td></td>
          </tr>      
          <tr>
            <td>runtime</td>
            <td>Integer</td>
            <td>-</td>
          </tr>      
           <tr>
            <td>genere</td>
            <td>string</td>
            <td>-</td>
          </tr>   
           <tr>
            <td>bookings</td>
            <td>Integer</td>
            <td>-</td>
          </tr>   
        </tbody>
      </table>


 


  version: 1.0.0
  
servers:
  - url: http://127.0.0.1:5000/
tags:
  - name: venue
    description: venue Management
  - name: show
    description: show Management
paths:
  /api/venueget/{venuein}:
    get:
      tags:
        - venue
      summary:  venues
      description: venues
      parameters:
        - in: path
          name: venuein
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Fetched successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  vid:
                    type: integer
                    example: 2
                  venue:
                    type: array
                    example: [names]
                    
        '404':
          description: not found
        '500':
          description: Internal Server Error
          
  /api/venuepost:
    post:
      tags:
        - venue
      summary: Create a new venue
      description:  venue
    
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cap:
                  type: integer
                  example: 88
                loc:
                  type: string
                  example: hyd
      responses:
        '200':
          description: created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  vid:
                    type: integer
                    example: 2
                  venue:
                    type: string
                    example: name
                  bookings:
                    type: integer
                    example: 7
                  loc:
                    type: string
                    example: hyd
                  
        '409':
          description:  already exists
        '500':
          description: Internal Server Error

  /api/venuedelete/{venuein}:
    delete:
      tags:
       - venue
      summary: Delete 
      description: Delete 
      parameters:
        - in: path
          name: venuein
          required: true
          schema:
            type: integer
            example: 2
      responses:
        '200':
          description: Successfully Deleted
        '404':
          description:  not found
        '500':
          description: Intenal Server Error
          
  /api/venueput/{venuein}:
    put:
      tags:
        - venue
      summary: Update 
      description: Update 
      parameters:
        - in: path
          name: venuein
          required: true
          schema:
            type: integer
            example: 2
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                venue:
                  type: string
                  example: hi
                loc:
                  type: string
                  example: hyd
      responses:
        '200':
          description:  updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                 
                  venue:
                    type: string
                    example: list_name
                  loc:
                    type: string
                    example: hyd
                 
        '404':
          description: not exists
        '500':
          description: Internal Server Error
          
  /api/showget/{showin}:
    get:
      tags:
        - show
      summary: shows
      description: list of all 
      parameters:
        - in: path
          name: showin
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Fetched successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  sid:
                    type: integer
                    example: 2
                  showname:
                    type: string
                    example: showname
                    
        '404':
          description: Card not found
        '500':
          description: Internal Server Error
  
  /api/showpost:
    post:
      tags:
        - show
      summary: Create 
      description: Create  
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                showname:
                  type: string
                  example: uf
                genre:
                  type: string
                  example: hyd
     
      responses:
        '201':
          description: created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  sid:
                    type: integer
                    example: 2
                  showname:
                    type: string
                    example: name
                  genre:
                    type: string
                    example: type
                
        '409':
          description:  already exists
        '500':
          description: Internal Server Error

  /api/showdelete/{showin}:
    delete:
      tags:
       - show
      summary: Delete
      description: Delete 
      parameters:
        - in: path
          name: showin
          required: true
          schema:
            type: integer
            example: 2
      responses:
        '200':
          description: Successfully Deleted
        '404':
          description: not found
        '500':
          description: Intenal Server Error
          
  /api/showput/{showin}:
    put:
      tags:
        - show
      summary: Update 
      description: Update
      parameters:
        - in: path
          name: showin
          required: true
          schema:
            type: integer
            example: 2
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                  sid:
                     type: integer
                     example: 2
                  showname:
                    type: string
                    example: name
                  genre:
                    type: string
                    example: type
               
      responses:
        '200':
          description:  updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  sid:
                     type: integer
                     example: 2
                  showname:
                    type: string
                    example: name
                  genre:
                    type: string
                    example: type
                
              
                  
        '404':
          description:  not exists
        '500':
          description: Internal Server Error